### ISSUE TITLE
Question: handling of unassigned rooms

### ISSUE THREAD

**Issue by Alex9779** [ChriD/node-raumkernel#29]
I have problems understanding how I can handle unassigned rooms and their devices.
This happens when I remove a room from a zone in the app.
The room is then unassigned and has no virtual renderer I can select.
I find the renderer on the zoneManager if I getRendererUdnsForRoomUdnOrName with the room name. 
How is it possible to reactivate that room with the raumkernel?

**Comment by ChriD** [comment]
You have to create a new zone with the unassigned room.
This can be achieved using "connectRoomToZone" method on the zoneManager
 with providing an empty "zonUdn" parameter

**Comment by Alex9779** [comment]
Ahhh ok got it... Thanks...
