### ISSUE TITLE
Using raumkernel, problems with logger

### ISSUE THREAD

**Issue by Alex9779** [ChriD/node-raumkernel#32]
Hi,
I finally started my implementation of node for node-red using your raumkernel to control some aspects of my Raumfeld system with Apples "Home" app. The real dependency is Node-Red -> MQTT Mosquitto -> homebridge-mqtt -> homebridge -> Home...
After some starting problems I think I got the trick how to achvie what I want so I started to implement my first nodes.
But I had one problem with the logger especially with this line:
https://github.com/ChriD/node-raumkernel/blob/0dd77ebb506d84a701cddb581d67f9c26ca25d63/lib/lib.logger.js#L64
This should create a file logger but starting the raumkernel in a node that is loaded in node-red this fails because it tries to create the file in the root directory.
As this is my first project with JS and Node.js I have no exact idea of what going on but as I thought I don't need a logfile for now, I just commented the line.

I think best would be to extend the logger creation with some addtional parameters to be able to select which logger end points should be created?

**Comment by Alex9779** [comment]
Oh BTW I tried to set a log path with the optional parameter but that didn't work out. I couldn't find a path working in the environtment when I load my stuff into node-red...

Maybe I just need a hint how to get that working...

**Comment by ChriD** [comment]
You may create your own logger and set it with `raumkernel.parmLogger(yourLoggerInstance)` before you call the `init() `method of the kernel
The `yourLoggerInstance` has to be  a derivative of the Logger class exposed in the raumkernel.

e.g for creating a logger which only emits the log with no output do something like.:
```
var RaumkernelLib = require('node-raumkernel')
class MyNewLogger extends RaumkernelLib.Logger {
 
    initExternalLogger()
    {
       // override the init of the winston logger
      // so do not call super() here!
    }
}

raumkernel.parmLogger(new MyNewLogger ())
```

**Comment by Alex9779** [comment]
Ahhh ok will try that. Thanks...

**Comment by Alex9779** [comment]
Ok for now I just created an empty logger doing nothing, thanks for the hint...
