### ISSUE TITLE
License of node-raumkernel

### ISSUE THREAD

**Issue by ulilicht** [ChriD/node-raumkernel#47]
Hello @ChriD, 

what is the license for this package? 

I would like to use node-raumkernel within a Mac App for controlling the Raumfeld Speakers. I plan to publish the code open source, but I need to publish binaries as well to make it easy for the users to use the Software. 

Can I use node-raumkernel for that? 
It would be great if you could add a license to this repository. (You can find descriptions here if you want: https://choosealicense.com) 

Best
Uli

**Comment by ChriD** [comment]
@ulilicht 
Sorry for the late response. You can do whatever you want with this code
I've added the MIT License
